
package com.example.localtest.smartstoreapi.seller.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SellerServicePortType", targetNamespace = "http://seller.shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SellerServicePortType {


    /**
     * 
     * @param placeProductOrderRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.PlaceProductOrderResponse
     */
    @WebMethod(operationName = "PlaceProductOrder")
    @WebResult(name = "PlaceProductOrderResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "PlaceProductOrderResponse")
    public PlaceProductOrderResponse placeProductOrder(
        @WebParam(name = "PlaceProductOrderRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "PlaceProductOrderRequest")
        PlaceProductOrderRequest placeProductOrderRequest);

    /**
     * 
     * @param withholdExchangeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.WithholdExchangeResponse
     */
    @WebMethod(operationName = "WithholdExchange")
    @WebResult(name = "WithholdExchangeResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "WithholdExchangeResponse")
    public WithholdExchangeResponse withholdExchange(
        @WebParam(name = "WithholdExchangeRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "WithholdExchangeRequest")
        WithholdExchangeRequest withholdExchangeRequest);

    /**
     * 
     * @param releaseExchangeHoldRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ReleaseExchangeHoldResponse
     */
    @WebMethod(operationName = "ReleaseExchangeHold")
    @WebResult(name = "ReleaseExchangeHoldResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ReleaseExchangeHoldResponse")
    public ReleaseExchangeHoldResponse releaseExchangeHold(
        @WebParam(name = "ReleaseExchangeHoldRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ReleaseExchangeHoldRequest")
        ReleaseExchangeHoldRequest releaseExchangeHoldRequest);

    /**
     * 
     * @param getProductOrderInfoListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.GetProductOrderInfoListResponse
     */
    @WebMethod(operationName = "GetProductOrderInfoList")
    @WebResult(name = "GetProductOrderInfoListResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "GetProductOrderInfoListResponse")
    public GetProductOrderInfoListResponse getProductOrderInfoList(
        @WebParam(name = "GetProductOrderInfoListRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "GetProductOrderInfoListRequest")
        GetProductOrderInfoListRequest getProductOrderInfoListRequest);

    /**
     * 
     * @param modifyECouponValidDateRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ModifyECouponValidDateResponse
     */
    @WebMethod(operationName = "ModifyECouponValidDate")
    @WebResult(name = "ModifyECouponValidDateResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ModifyECouponValidDateResponse")
    public ModifyECouponValidDateResponse modifyECouponValidDate(
        @WebParam(name = "ModifyECouponValidDateRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ModifyECouponValidDateRequest")
        ModifyECouponValidDateRequest modifyECouponValidDateRequest);

    /**
     * 
     * @param useECouponRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.UseECouponResponse
     */
    @WebMethod(operationName = "UseECoupon")
    @WebResult(name = "UseECouponResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "UseECouponResponse")
    public UseECouponResponse useECoupon(
        @WebParam(name = "UseECouponRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "UseECouponRequest")
        UseECouponRequest useECouponRequest);

    /**
     * 
     * @param approveCollectedExchangeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ApproveCollectedExchangeResponse
     */
    @WebMethod(operationName = "ApproveCollectedExchange")
    @WebResult(name = "ApproveCollectedExchangeResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ApproveCollectedExchangeResponse")
    public ApproveCollectedExchangeResponse approveCollectedExchange(
        @WebParam(name = "ApproveCollectedExchangeRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ApproveCollectedExchangeRequest")
        ApproveCollectedExchangeRequest approveCollectedExchangeRequest);

    /**
     * 
     * @param approveReturnApplicationRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ApproveReturnApplicationResponse
     */
    @WebMethod(operationName = "ApproveReturnApplication")
    @WebResult(name = "ApproveReturnApplicationResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ApproveReturnApplicationResponse")
    public ApproveReturnApplicationResponse approveReturnApplication(
        @WebParam(name = "ApproveReturnApplicationRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ApproveReturnApplicationRequest")
        ApproveReturnApplicationRequest approveReturnApplicationRequest);

    /**
     * 
     * @param shipProductOrderRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ShipProductOrderResponse
     */
    @WebMethod(operationName = "ShipProductOrder")
    @WebResult(name = "ShipProductOrderResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ShipProductOrderResponse")
    public ShipProductOrderResponse shipProductOrder(
        @WebParam(name = "ShipProductOrderRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ShipProductOrderRequest")
        ShipProductOrderRequest shipProductOrderRequest);

    /**
     * 
     * @param withholdReturnRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.WithholdReturnResponse
     */
    @WebMethod(operationName = "WithholdReturn")
    @WebResult(name = "WithholdReturnResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "WithholdReturnResponse")
    public WithholdReturnResponse withholdReturn(
        @WebParam(name = "WithholdReturnRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "WithholdReturnRequest")
        WithholdReturnRequest withholdReturnRequest);

    /**
     * 
     * @param changeECouponStatusRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ChangeECouponStatusResponse
     */
    @WebMethod(operationName = "ChangeECouponStatus")
    @WebResult(name = "ChangeECouponStatusResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ChangeECouponStatusResponse")
    public ChangeECouponStatusResponse changeECouponStatus(
        @WebParam(name = "ChangeECouponStatusRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ChangeECouponStatusRequest")
        ChangeECouponStatusRequest changeECouponStatusRequest);

    /**
     * 
     * @param delayProductOrderRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.DelayProductOrderResponse
     */
    @WebMethod(operationName = "DelayProductOrder")
    @WebResult(name = "DelayProductOrderResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "DelayProductOrderResponse")
    public DelayProductOrderResponse delayProductOrder(
        @WebParam(name = "DelayProductOrderRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "DelayProductOrderRequest")
        DelayProductOrderRequest delayProductOrderRequest);

    /**
     * 
     * @param releaseReturnHoldRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ReleaseReturnHoldResponse
     */
    @WebMethod(operationName = "ReleaseReturnHold")
    @WebResult(name = "ReleaseReturnHoldResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ReleaseReturnHoldResponse")
    public ReleaseReturnHoldResponse releaseReturnHold(
        @WebParam(name = "ReleaseReturnHoldRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ReleaseReturnHoldRequest")
        ReleaseReturnHoldRequest releaseReturnHoldRequest);

    /**
     * 
     * @param cancelSaleRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.CancelSaleResponse
     */
    @WebMethod(operationName = "CancelSale")
    @WebResult(name = "CancelSaleResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "CancelSaleResponse")
    public CancelSaleResponse cancelSale(
        @WebParam(name = "CancelSaleRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "CancelSaleRequest")
        CancelSaleRequest cancelSaleRequest);

    /**
     * 
     * @param requestReturnRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.RequestReturnResponse
     */
    @WebMethod(operationName = "RequestReturn")
    @WebResult(name = "RequestReturnResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "RequestReturnResponse")
    public RequestReturnResponse requestReturn(
        @WebParam(name = "RequestReturnRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "RequestReturnRequest")
        RequestReturnRequest requestReturnRequest);

    /**
     * 
     * @param reDeliveryExchangeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ReDeliveryExchangeResponse
     */
    @WebMethod(operationName = "ReDeliveryExchange")
    @WebResult(name = "ReDeliveryExchangeResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ReDeliveryExchangeResponse")
    public ReDeliveryExchangeResponse reDeliveryExchange(
        @WebParam(name = "ReDeliveryExchangeRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ReDeliveryExchangeRequest")
        ReDeliveryExchangeRequest reDeliveryExchangeRequest);

    /**
     * 
     * @param rejectExchangeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.RejectExchangeResponse
     */
    @WebMethod(operationName = "RejectExchange")
    @WebResult(name = "RejectExchangeResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "RejectExchangeResponse")
    public RejectExchangeResponse rejectExchange(
        @WebParam(name = "RejectExchangeRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "RejectExchangeRequest")
        RejectExchangeRequest rejectExchangeRequest);

    /**
     * 
     * @param approveCancelApplicationRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.ApproveCancelApplicationResponse
     */
    @WebMethod(operationName = "ApproveCancelApplication")
    @WebResult(name = "ApproveCancelApplicationResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ApproveCancelApplicationResponse")
    public ApproveCancelApplicationResponse approveCancelApplication(
        @WebParam(name = "ApproveCancelApplicationRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "ApproveCancelApplicationRequest")
        ApproveCancelApplicationRequest approveCancelApplicationRequest);

    /**
     * 
     * @param rejectReturnRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.RejectReturnResponse
     */
    @WebMethod(operationName = "RejectReturn")
    @WebResult(name = "RejectReturnResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "RejectReturnResponse")
    public RejectReturnResponse rejectReturn(
        @WebParam(name = "RejectReturnRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "RejectReturnRequest")
        RejectReturnRequest rejectReturnRequest);

    /**
     * 
     * @param getProductOrderIDListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.GetProductOrderIdListResponse
     */
    @WebMethod(operationName = "GetProductOrderIDList")
    @WebResult(name = "GetProductOrderIDListResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "GetProductOrderIDListResponse")
    public GetProductOrderIdListResponse getProductOrderIDList(
        @WebParam(name = "GetProductOrderIDListRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "GetProductOrderIDListRequest")
        GetProductOrderIdListRequest getProductOrderIDListRequest);

    /**
     * 
     * @param getChangedProductOrderListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.seller.GetChangedProductOrderListResponse
     */
    @WebMethod(operationName = "GetChangedProductOrderList")
    @WebResult(name = "GetChangedProductOrderListResponse", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "GetChangedProductOrderListResponse")
    public GetChangedProductOrderListResponse getChangedProductOrderList(
        @WebParam(name = "GetChangedProductOrderListRequest", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", partName = "GetChangedProductOrderListRequest")
        GetChangedProductOrderListRequest getChangedProductOrderListRequest);

}
