
package com.example.localtest.smartstoreapi.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddressBookServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressBookServicePortType {


    /**
     * 
     * @param getAddressBookListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetAddressBookListResponseType
     */
    @WebMethod(operationName = "GetAddressBookList", action = "AddressBookService#GetAddressBookList")
    @WebResult(name = "GetAddressBookListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAddressBookListResponse")
    public GetAddressBookListResponseType getAddressBookList(
        @WebParam(name = "GetAddressBookListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAddressBookListRequest")
        GetAddressBookListRequestType getAddressBookListRequest);

}
