
package com.example.localtest.smartstoreapi.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeliveryInfoServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeliveryInfoServicePortType {


    /**
     * 
     * @param getBundleGroupListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetBundleGroupListResponseType
     */
    @WebMethod(operationName = "GetBundleGroupList", action = "DeliveryInfoService#GetBundleGroupList")
    @WebResult(name = "GetBundleGroupListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupListResponse")
    public GetBundleGroupListResponseType getBundleGroupList(
        @WebParam(name = "GetBundleGroupListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupListRequest")
        GetBundleGroupListRequestType getBundleGroupListRequest);

    /**
     * 
     * @param getReturnsCompanyListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetReturnsCompanyListResponseType
     */
    @WebMethod(operationName = "GetReturnsCompanyList", action = "DeliveryInfoService#GetReturnsCompanyList")
    @WebResult(name = "GetReturnsCompanyListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetReturnsCompanyListResponse")
    public GetReturnsCompanyListResponseType getReturnsCompanyList(
        @WebParam(name = "GetReturnsCompanyListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetReturnsCompanyListRequest")
        GetReturnsCompanyListRequestType getReturnsCompanyListRequest);

    /**
     * 
     * @param manageBundleGroupRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageBundleGroupResponseType
     */
    @WebMethod(operationName = "ManageBundleGroup", action = "DeliveryInfoService#ManageBundleGroup")
    @WebResult(name = "ManageBundleGroupResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageBundleGroupResponse")
    public ManageBundleGroupResponseType manageBundleGroup(
        @WebParam(name = "ManageBundleGroupRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageBundleGroupRequest")
        ManageBundleGroupRequestType manageBundleGroupRequest);

    /**
     * 
     * @param getBundleGroupRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetBundleGroupResponseType
     */
    @WebMethod(operationName = "GetBundleGroup", action = "DeliveryInfoService#GetBundleGroup")
    @WebResult(name = "GetBundleGroupResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupResponse")
    public GetBundleGroupResponseType getBundleGroup(
        @WebParam(name = "GetBundleGroupRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupRequest")
        GetBundleGroupRequestType getBundleGroupRequest);

    /**
     * 
     * @param getHopeDeliveryGroupRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetHopeDeliveryGroupResponseType
     */
    @WebMethod(operationName = "GetHopeDeliveryGroup", action = "DeliveryInfoService#GetHopeDeliveryGroup")
    @WebResult(name = "GetHopeDeliveryGroupResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetHopeDeliveryGroupResponse")
    public GetHopeDeliveryGroupResponseType getHopeDeliveryGroup(
        @WebParam(name = "GetHopeDeliveryGroupRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetHopeDeliveryGroupRequest")
        GetHopeDeliveryGroupRequestType getHopeDeliveryGroupRequest);

    /**
     * 
     * @param getHopeDeliveryGroupListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetHopeDeliveryGroupListResponseType
     */
    @WebMethod(operationName = "GetHopeDeliveryGroupList", action = "DeliveryInfoService#GetHopeDeliveryGroupList")
    @WebResult(name = "GetHopeDeliveryGroupListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetHopeDeliveryGroupListResponse")
    public GetHopeDeliveryGroupListResponseType getHopeDeliveryGroupList(
        @WebParam(name = "GetHopeDeliveryGroupListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetHopeDeliveryGroupListRequest")
        GetHopeDeliveryGroupListRequestType getHopeDeliveryGroupListRequest);

    /**
     * 
     * @param manageHopeDeliveryGroupRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageHopeDeliveryGroupResponseType
     */
    @WebMethod(operationName = "ManageHopeDeliveryGroup", action = "DeliveryInfoService#ManageHopeDeliveryGroup")
    @WebResult(name = "ManageHopeDeliveryGroupResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageHopeDeliveryGroupResponse")
    public ManageHopeDeliveryGroupResponseType manageHopeDeliveryGroup(
        @WebParam(name = "ManageHopeDeliveryGroupRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageHopeDeliveryGroupRequest")
        ManageHopeDeliveryGroupRequestType manageHopeDeliveryGroupRequest);

}
