
package com.example.localtest.smartstoreapi.product.type;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GalleryService", targetNamespace = "http://shopn.platform.nhncorp.com/", wsdlLocation = "file:/Users/seotaewan/smart-store/src/main/resources/wsdl/product/ShopNAPI.wsdl")
public class GalleryService
    extends Service
{

    private final static URL GALLERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException GALLERYSERVICE_EXCEPTION;
    private final static QName GALLERYSERVICE_QNAME = new QName("http://shopn.platform.nhncorp.com/", "GalleryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/seotaewan/smart-store/src/main/resources/wsdl/product/ShopNAPI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GALLERYSERVICE_WSDL_LOCATION = url;
        GALLERYSERVICE_EXCEPTION = e;
    }

    public GalleryService() {
        super(__getWsdlLocation(), GALLERYSERVICE_QNAME);
    }

    public GalleryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GALLERYSERVICE_QNAME, features);
    }

    public GalleryService(URL wsdlLocation) {
        super(wsdlLocation, GALLERYSERVICE_QNAME);
    }

    public GalleryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GALLERYSERVICE_QNAME, features);
    }

    public GalleryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GalleryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GalleryServicePortType
     */
    @WebEndpoint(name = "GalleryServiceSOAP11port_http")
    public GalleryServicePortType getGalleryServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "GalleryServiceSOAP11port_http"), GalleryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GalleryServicePortType
     */
    @WebEndpoint(name = "GalleryServiceSOAP11port_http")
    public GalleryServicePortType getGalleryServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "GalleryServiceSOAP11port_http"), GalleryServicePortType.class, features);
    }

    /**
     *
     * @return
     *     returns GalleryServicePortType
     */
    @WebEndpoint(name = "GalleryServiceSOAP12port_http")
    public GalleryServicePortType getGalleryServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "GalleryServiceSOAP12port_http"), GalleryServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GalleryServicePortType
     */
    @WebEndpoint(name = "GalleryServiceSOAP12port_http")
    public GalleryServicePortType getGalleryServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "GalleryServiceSOAP12port_http"), GalleryServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GALLERYSERVICE_EXCEPTION!= null) {
            throw GALLERYSERVICE_EXCEPTION;
        }
        return GALLERYSERVICE_WSDL_LOCATION;
    }

}
