
package com.example.localtest.smartstoreapi.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImageServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImageServicePortType {


    /**
     * 
     * @param uploadImageRequest
     * @return
     *     returns com.nhncorp.platform.shopn.UploadImageResponseType
     */
    @WebMethod(operationName = "UploadImage", action = "ImageService#UploadImage")
    @WebResult(name = "UploadImageResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "UploadImageResponse")
    public UploadImageResponseType uploadImage(
        @WebParam(name = "UploadImageRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "UploadImageRequest")
        UploadImageRequestType uploadImageRequest);

}
