
package com.example.localtest.smartstoreapi.product.type;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuestionAnswerService", targetNamespace = "http://shopn.platform.nhncorp.com/", wsdlLocation = "file:./src/main/resources/wsdl/product/ShopNAPI.wsdl")
public class QuestionAnswerService
    extends Service
{

    private final static URL QUESTIONANSWERSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUESTIONANSWERSERVICE_EXCEPTION;
    private final static QName QUESTIONANSWERSERVICE_QNAME = new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:./src/main/resources/wsdl/product/ShopNAPI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUESTIONANSWERSERVICE_WSDL_LOCATION = url;
        QUESTIONANSWERSERVICE_EXCEPTION = e;
    }

    public QuestionAnswerService() {
        super(__getWsdlLocation(), QUESTIONANSWERSERVICE_QNAME);
    }

    public QuestionAnswerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUESTIONANSWERSERVICE_QNAME, features);
    }

    public QuestionAnswerService(URL wsdlLocation) {
        super(wsdlLocation, QUESTIONANSWERSERVICE_QNAME);
    }

    public QuestionAnswerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUESTIONANSWERSERVICE_QNAME, features);
    }

    public QuestionAnswerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuestionAnswerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP11port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP11port_http"), QuestionAnswerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP11port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP11port_http"), QuestionAnswerServicePortType.class, features);
    }

    /**
     *
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP12port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP12port_http"), QuestionAnswerServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP12port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP12port_http"), QuestionAnswerServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUESTIONANSWERSERVICE_EXCEPTION!= null) {
            throw QUESTIONANSWERSERVICE_EXCEPTION;
        }
        return QUESTIONANSWERSERVICE_WSDL_LOCATION;
    }

}
