
package com.example.localtest.smartstoreapi.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QuestionAnswerServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuestionAnswerServicePortType {


    /**
     * 
     * @param getQuestionAnswerListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetQuestionAnswerListResponseType
     */
    @WebMethod(operationName = "GetQuestionAnswerList", action = "QuestionAnswerService#GetQuestionAnswerList")
    @WebResult(name = "GetQuestionAnswerListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetQuestionAnswerListResponse")
    public GetQuestionAnswerListResponseType getQuestionAnswerList(
        @WebParam(name = "GetQuestionAnswerListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetQuestionAnswerListRequest")
        GetQuestionAnswerListRequestType getQuestionAnswerListRequest);

    /**
     * 
     * @param getQuestionAnswerTemplateListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetQuestionAnswerTemplateListResponseType
     */
    @WebMethod(operationName = "GetQuestionAnswerTemplateList", action = "QuestionAnswerService#GetQuestionAnswerTemplateList")
    @WebResult(name = "GetQuestionAnswerTemplateListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetQuestionAnswerTemplateListResponse")
    public GetQuestionAnswerTemplateListResponseType getQuestionAnswerTemplateList(
        @WebParam(name = "GetQuestionAnswerTemplateListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetQuestionAnswerTemplateListRequest")
        GetQuestionAnswerTemplateListRequestType getQuestionAnswerTemplateListRequest);

    /**
     * 
     * @param manageQuestionAnswerRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageQuestionAnswerResponseType
     */
    @WebMethod(operationName = "ManageQuestionAnswer", action = "QuestionAnswerService#ManageQuestionAnswer")
    @WebResult(name = "ManageQuestionAnswerResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageQuestionAnswerResponse")
    public ManageQuestionAnswerResponseType manageQuestionAnswer(
        @WebParam(name = "ManageQuestionAnswerRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageQuestionAnswerRequest")
        ManageQuestionAnswerRequestType manageQuestionAnswerRequest);

}
