
package com.example.localtest.smartstoreapi.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegisterSellerServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegisterSellerServicePortType {


    /**
     * 
     * @param registerSellerRequest
     * @return
     *     returns com.nhncorp.platform.shopn.RegisterSellerResponseType
     */
    @WebMethod(operationName = "RegisterSeller", action = "RegisterSellerService#RegisterSeller")
    @WebResult(name = "RegisterSellerResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "RegisterSellerResponse")
    public RegisterSellerResponseType registerSeller(
        @WebParam(name = "RegisterSellerRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "RegisterSellerRequest")
        RegisterSellerRequestType registerSellerRequest);

}
