
package com.example.localtest.smartstoreapi.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SellerNoticeServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SellerNoticeServicePortType {


    /**
     * 
     * @param applySellerNoticeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ApplySellerNoticeResponseType
     */
    @WebMethod(operationName = "ApplySellerNotice", action = "SellerNoticeService#ApplySellerNotice")
    @WebResult(name = "ApplySellerNoticeResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ApplySellerNoticeResponse")
    public ApplySellerNoticeResponseType applySellerNotice(
        @WebParam(name = "ApplySellerNoticeRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ApplySellerNoticeRequest")
        ApplySellerNoticeRequestType applySellerNoticeRequest);

    /**
     * 
     * @param deleteSellerNoticeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.DeleteSellerNoticeResponseType
     */
    @WebMethod(operationName = "DeleteSellerNotice", action = "SellerNoticeService#DeleteSellerNotice")
    @WebResult(name = "DeleteSellerNoticeResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "DeleteSellerNoticeResponse")
    public DeleteSellerNoticeResponseType deleteSellerNotice(
        @WebParam(name = "DeleteSellerNoticeRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "DeleteSellerNoticeRequest")
        DeleteSellerNoticeRequestType deleteSellerNoticeRequest);

    /**
     * 
     * @param getSellerNoticeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetSellerNoticeResponseType
     */
    @WebMethod(operationName = "GetSellerNotice", action = "SellerNoticeService#GetSellerNotice")
    @WebResult(name = "GetSellerNoticeResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSellerNoticeResponse")
    public GetSellerNoticeResponseType getSellerNotice(
        @WebParam(name = "GetSellerNoticeRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSellerNoticeRequest")
        GetSellerNoticeRequestType getSellerNoticeRequest);

    /**
     * 
     * @param getSellerNoticeListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetSellerNoticeListResponseType
     */
    @WebMethod(operationName = "GetSellerNoticeList", action = "SellerNoticeService#GetSellerNoticeList")
    @WebResult(name = "GetSellerNoticeListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSellerNoticeListResponse")
    public GetSellerNoticeListResponseType getSellerNoticeList(
        @WebParam(name = "GetSellerNoticeListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSellerNoticeListRequest")
        GetSellerNoticeListRequestType getSellerNoticeListRequest);

    /**
     * 
     * @param manageSellerNoticeRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageSellerNoticeResponseType
     */
    @WebMethod(operationName = "ManageSellerNotice", action = "SellerNoticeService#ManageSellerNotice")
    @WebResult(name = "ManageSellerNoticeResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageSellerNoticeResponse")
    public ManageSellerNoticeResponseType manageSellerNotice(
        @WebParam(name = "ManageSellerNoticeRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageSellerNoticeRequest")
        ManageSellerNoticeRequestType manageSellerNoticeRequest);

}
