
package com.example.localtest.smartstoreapi.product.type;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SellerNoticeService", targetNamespace = "http://shopn.platform.nhncorp.com/", wsdlLocation = "file:./src/main/resources/wsdl/product/ShopNAPI.wsdl")
public class SellerNoticeService
    extends Service
{

    private final static URL SELLERNOTICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SELLERNOTICESERVICE_EXCEPTION;
    private final static QName SELLERNOTICESERVICE_QNAME = new QName("http://shopn.platform.nhncorp.com/", "SellerNoticeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:./src/main/resources/wsdl/product/ShopNAPI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SELLERNOTICESERVICE_WSDL_LOCATION = url;
        SELLERNOTICESERVICE_EXCEPTION = e;
    }

    public SellerNoticeService() {
        super(__getWsdlLocation(), SELLERNOTICESERVICE_QNAME);
    }

    public SellerNoticeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SELLERNOTICESERVICE_QNAME, features);
    }

    public SellerNoticeService(URL wsdlLocation) {
        super(wsdlLocation, SELLERNOTICESERVICE_QNAME);
    }

    public SellerNoticeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SELLERNOTICESERVICE_QNAME, features);
    }

    public SellerNoticeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SellerNoticeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SellerNoticeServicePortType
     */
    @WebEndpoint(name = "SellerNoticeServiceSOAP11port_http")
    public SellerNoticeServicePortType getSellerNoticeServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "SellerNoticeServiceSOAP11port_http"), SellerNoticeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellerNoticeServicePortType
     */
    @WebEndpoint(name = "SellerNoticeServiceSOAP11port_http")
    public SellerNoticeServicePortType getSellerNoticeServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "SellerNoticeServiceSOAP11port_http"), SellerNoticeServicePortType.class, features);
    }

    /**
     *
     * @return
     *     returns SellerNoticeServicePortType
     */
    @WebEndpoint(name = "SellerNoticeServiceSOAP12port_http")
    public SellerNoticeServicePortType getSellerNoticeServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "SellerNoticeServiceSOAP12port_http"), SellerNoticeServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellerNoticeServicePortType
     */
    @WebEndpoint(name = "SellerNoticeServiceSOAP12port_http")
    public SellerNoticeServicePortType getSellerNoticeServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "SellerNoticeServiceSOAP12port_http"), SellerNoticeServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SELLERNOTICESERVICE_EXCEPTION!= null) {
            throw SELLERNOTICESERVICE_EXCEPTION;
        }
        return SELLERNOTICESERVICE_WSDL_LOCATION;
    }

}
