
package com.example.localtest.smartstore.customer.type;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerInquiryService", targetNamespace = "http://customerinquiry.shopn.platform.nhncorp.com/", wsdlLocation = "file:/Users/sh/Documents/private/worspaces/local-test/src/main/resources/wsdl/customer/CustomerInquiryService.wsdl")
public class CustomerInquiryService
    extends Service
{

    private final static URL CUSTOMERINQUIRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERINQUIRYSERVICE_EXCEPTION;
    private final static QName CUSTOMERINQUIRYSERVICE_QNAME = new QName("http://customerinquiry.shopn.platform.nhncorp.com/", "CustomerInquiryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/sh/Documents/private/worspaces/local-test/src/main/resources/wsdl/customer/CustomerInquiryService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERINQUIRYSERVICE_WSDL_LOCATION = url;
        CUSTOMERINQUIRYSERVICE_EXCEPTION = e;
    }

    public CustomerInquiryService() {
        super(__getWsdlLocation(), CUSTOMERINQUIRYSERVICE_QNAME);
    }

    public CustomerInquiryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERINQUIRYSERVICE_QNAME, features);
    }

    public CustomerInquiryService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERINQUIRYSERVICE_QNAME);
    }

    public CustomerInquiryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERINQUIRYSERVICE_QNAME, features);
    }

    public CustomerInquiryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerInquiryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerInquiryServicePortType
     */
    @WebEndpoint(name = "CustomerInquiryServiceSOAP11port_http")
    public CustomerInquiryServicePortType getCustomerInquiryServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://customerinquiry.shopn.platform.nhncorp.com/", "CustomerInquiryServiceSOAP11port_http"), CustomerInquiryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerInquiryServicePortType
     */
    @WebEndpoint(name = "CustomerInquiryServiceSOAP11port_http")
    public CustomerInquiryServicePortType getCustomerInquiryServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://customerinquiry.shopn.platform.nhncorp.com/", "CustomerInquiryServiceSOAP11port_http"), CustomerInquiryServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns CustomerInquiryServicePortType
     */
    @WebEndpoint(name = "CustomerInquiryServiceSOAP12port_http")
    public CustomerInquiryServicePortType getCustomerInquiryServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://customerinquiry.shopn.platform.nhncorp.com/", "CustomerInquiryServiceSOAP12port_http"), CustomerInquiryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerInquiryServicePortType
     */
    @WebEndpoint(name = "CustomerInquiryServiceSOAP12port_http")
    public CustomerInquiryServicePortType getCustomerInquiryServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://customerinquiry.shopn.platform.nhncorp.com/", "CustomerInquiryServiceSOAP12port_http"), CustomerInquiryServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERINQUIRYSERVICE_EXCEPTION!= null) {
            throw CUSTOMERINQUIRYSERVICE_EXCEPTION;
        }
        return CUSTOMERINQUIRYSERVICE_WSDL_LOCATION;
    }

}
