
package com.example.localtest.smartstore.seller.type;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SellerService", targetNamespace = "http://seller.shopn.platform.nhncorp.com/", wsdlLocation = "file:/Users/seotaewan/smart-store/src/main/resources/wsdl/seller/SellerService.wsdl")
public class SellerService
    extends Service
{

    private final static URL SELLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SELLERSERVICE_EXCEPTION;
    private final static QName SELLERSERVICE_QNAME = new QName("http://seller.shopn.platform.nhncorp.com/", "SellerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/seotaewan/smart-store/src/main/resources/wsdl/seller/SellerService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SELLERSERVICE_WSDL_LOCATION = url;
        SELLERSERVICE_EXCEPTION = e;
    }

    public SellerService() {
        super(__getWsdlLocation(), SELLERSERVICE_QNAME);
    }

    public SellerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SELLERSERVICE_QNAME, features);
    }

    public SellerService(URL wsdlLocation) {
        super(wsdlLocation, SELLERSERVICE_QNAME);
    }

    public SellerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SELLERSERVICE_QNAME, features);
    }

    public SellerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SellerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SellerServicePortType
     */
    @WebEndpoint(name = "SellerServiceSOAP11Port")
    public SellerServicePortType getSellerServiceSOAP11Port() {
        return super.getPort(new QName("http://seller.shopn.platform.nhncorp.com/", "SellerServiceSOAP11Port"), SellerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellerServicePortType
     */
    @WebEndpoint(name = "SellerServiceSOAP11Port")
    public SellerServicePortType getSellerServiceSOAP11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://seller.shopn.platform.nhncorp.com/", "SellerServiceSOAP11Port"), SellerServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns SellerServicePortType
     */
    @WebEndpoint(name = "SellerServiceSOAP12Port")
    public SellerServicePortType getSellerServiceSOAP12Port() {
        return super.getPort(new QName("http://seller.shopn.platform.nhncorp.com/", "SellerServiceSOAP12Port"), SellerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellerServicePortType
     */
    @WebEndpoint(name = "SellerServiceSOAP12Port")
    public SellerServicePortType getSellerServiceSOAP12Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://seller.shopn.platform.nhncorp.com/", "SellerServiceSOAP12Port"), SellerServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SELLERSERVICE_EXCEPTION!= null) {
            throw SELLERSERVICE_EXCEPTION;
        }
        return SELLERSERVICE_WSDL_LOCATION;
    }

}
