
package com.example.localtest.smartstore.product.type;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeliveryInfoService", targetNamespace = "http://shopn.platform.nhncorp.com/", wsdlLocation = "file:/Users/sh/Documents/private/worspaces/local-test/src/main/resources/wsdl/product/ShopNAPI.wsdl")
public class DeliveryInfoService
    extends Service
{

    private final static URL DELIVERYINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYINFOSERVICE_EXCEPTION;
    private final static QName DELIVERYINFOSERVICE_QNAME = new QName("http://shopn.platform.nhncorp.com/", "DeliveryInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/sh/Documents/private/worspaces/local-test/src/main/resources/wsdl/product/ShopNAPI.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYINFOSERVICE_WSDL_LOCATION = url;
        DELIVERYINFOSERVICE_EXCEPTION = e;
    }

    public DeliveryInfoService() {
        super(__getWsdlLocation(), DELIVERYINFOSERVICE_QNAME);
    }

    public DeliveryInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYINFOSERVICE_QNAME, features);
    }

    public DeliveryInfoService(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYINFOSERVICE_QNAME);
    }

    public DeliveryInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYINFOSERVICE_QNAME, features);
    }

    public DeliveryInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryInfoServicePortType
     */
    @WebEndpoint(name = "DeliveryInfoServiceSOAP11port_http")
    public DeliveryInfoServicePortType getDeliveryInfoServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "DeliveryInfoServiceSOAP11port_http"), DeliveryInfoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryInfoServicePortType
     */
    @WebEndpoint(name = "DeliveryInfoServiceSOAP11port_http")
    public DeliveryInfoServicePortType getDeliveryInfoServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "DeliveryInfoServiceSOAP11port_http"), DeliveryInfoServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryInfoServicePortType
     */
    @WebEndpoint(name = "DeliveryInfoServiceSOAP12port_http")
    public DeliveryInfoServicePortType getDeliveryInfoServiceSOAP12PortHttp() {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "DeliveryInfoServiceSOAP12port_http"), DeliveryInfoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryInfoServicePortType
     */
    @WebEndpoint(name = "DeliveryInfoServiceSOAP12port_http")
    public DeliveryInfoServicePortType getDeliveryInfoServiceSOAP12PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://shopn.platform.nhncorp.com/", "DeliveryInfoServiceSOAP12port_http"), DeliveryInfoServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYINFOSERVICE_EXCEPTION!= null) {
            throw DELIVERYINFOSERVICE_EXCEPTION;
        }
        return DELIVERYINFOSERVICE_WSDL_LOCATION;
    }

}
