
package com.example.localtest.smartstore.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GalleryServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GalleryServicePortType {


    /**
     * 
     * @param applyGalleryRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ApplyGalleryResponseType
     */
    @WebMethod(operationName = "ApplyGallery", action = "GalleryService#ApplyGallery")
    @WebResult(name = "ApplyGalleryResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ApplyGalleryResponse")
    public ApplyGalleryResponseType applyGallery(
        @WebParam(name = "ApplyGalleryRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ApplyGalleryRequest")
        ApplyGalleryRequestType applyGalleryRequest);

    /**
     * 
     * @param getGalleryRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetGalleryResponseType
     */
    @WebMethod(operationName = "GetGallery", action = "GalleryService#GetGallery")
    @WebResult(name = "GetGalleryResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetGalleryResponse")
    public GetGalleryResponseType getGallery(
        @WebParam(name = "GetGalleryRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetGalleryRequest")
        GetGalleryRequestType getGalleryRequest);

    /**
     * 
     * @param getGalleryListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetGalleryListResponseType
     */
    @WebMethod(operationName = "GetGalleryList", action = "GalleryService#GetGalleryList")
    @WebResult(name = "GetGalleryListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetGalleryListResponse")
    public GetGalleryListResponseType getGalleryList(
        @WebParam(name = "GetGalleryListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetGalleryListRequest")
        GetGalleryListRequestType getGalleryListRequest);

    /**
     * 
     * @param manageGalleryRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageGalleryResponseType
     */
    @WebMethod(operationName = "ManageGallery", action = "GalleryService#ManageGallery")
    @WebResult(name = "ManageGalleryResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageGalleryResponse")
    public ManageGalleryResponseType manageGallery(
        @WebParam(name = "ManageGalleryRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageGalleryRequest")
        ManageGalleryRequestType manageGalleryRequest);

}
