
package com.example.localtest.smartstore.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServicePortType {


    /**
     * 
     * @param changeProductSaleStatusRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ChangeProductSaleStatusResponseType
     */
    @WebMethod(operationName = "ChangeProductSaleStatus", action = "ProductService#ChangeProductSaleStatus")
    @WebResult(name = "ChangeProductSaleStatusResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ChangeProductSaleStatusResponse")
    public ChangeProductSaleStatusResponseType changeProductSaleStatus(
        @WebParam(name = "ChangeProductSaleStatusRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ChangeProductSaleStatusRequest")
        ChangeProductSaleStatusRequestType changeProductSaleStatusRequest);

    /**
     * 
     * @param getAllCategoryListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetAllCategoryListResponseType
     */
    @WebMethod(operationName = "GetAllCategoryList", action = "ProductService#GetAllCategoryList")
    @WebResult(name = "GetAllCategoryListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllCategoryListResponse")
    public GetAllCategoryListResponseType getAllCategoryList(
        @WebParam(name = "GetAllCategoryListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllCategoryListRequest")
        GetAllCategoryListRequestType getAllCategoryListRequest);

    /**
     * 
     * @param getAttributeListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetAttributeListResponseType
     */
    @WebMethod(operationName = "GetAttributeList", action = "ProductService#GetAttributeList")
    @WebResult(name = "GetAttributeListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAttributeListResponse")
    public GetAttributeListResponseType getAttributeList(
        @WebParam(name = "GetAttributeListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAttributeListRequest")
        GetAttributeListRequestType getAttributeListRequest);

    /**
     * 
     * @param getAttributeValueListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetAttributeValueListResponseType
     */
    @WebMethod(operationName = "GetAttributeValueList", action = "ProductService#GetAttributeValueList")
    @WebResult(name = "GetAttributeValueListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAttributeValueListResponse")
    public GetAttributeValueListResponseType getAttributeValueList(
        @WebParam(name = "GetAttributeValueListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAttributeValueListRequest")
        GetAttributeValueListRequestType getAttributeValueListRequest);

    /**
     * 
     * @param getAttributeValueUnitListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetAttributeValueUnitListResponseType
     */
    @WebMethod(operationName = "GetAttributeValueUnitList", action = "ProductService#GetAttributeValueUnitList")
    @WebResult(name = "GetAttributeValueUnitListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAttributeValueUnitListResponse")
    public GetAttributeValueUnitListResponseType getAttributeValueUnitList(
        @WebParam(name = "GetAttributeValueUnitListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAttributeValueUnitListRequest")
        GetAttributeValueUnitListRequestType getAttributeValueUnitListRequest);

    /**
     * 
     * @param getBrandListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetBrandListResponseType
     */
    @WebMethod(operationName = "GetBrandList", action = "ProductService#GetBrandList")
    @WebResult(name = "GetBrandListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBrandListResponse")
    public GetBrandListResponseType getBrandList(
        @WebParam(name = "GetBrandListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBrandListRequest")
        GetBrandListRequestType getBrandListRequest);

    /**
     * 
     * @param getCategoryInfoRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetCategoryInfoResponseType
     */
    @WebMethod(operationName = "GetCategoryInfo", action = "ProductService#GetCategoryInfo")
    @WebResult(name = "GetCategoryInfoResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetCategoryInfoResponse")
    public GetCategoryInfoResponseType getCategoryInfo(
        @WebParam(name = "GetCategoryInfoRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetCategoryInfoRequest")
        GetCategoryInfoRequestType getCategoryInfoRequest);

    /**
     * 
     * @param getManufacturerListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetManufacturerListResponseType
     */
    @WebMethod(operationName = "GetManufacturerList", action = "ProductService#GetManufacturerList")
    @WebResult(name = "GetManufacturerListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetManufacturerListResponse")
    public GetManufacturerListResponseType getManufacturerList(
        @WebParam(name = "GetManufacturerListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetManufacturerListRequest")
        GetManufacturerListRequestType getManufacturerListRequest);

    /**
     * 
     * @param getModelListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetModelListResponseType
     */
    @WebMethod(operationName = "GetModelList", action = "ProductService#GetModelList")
    @WebResult(name = "GetModelListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModelListResponse")
    public GetModelListResponseType getModelList(
        @WebParam(name = "GetModelListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModelListRequest")
        GetModelListRequestType getModelListRequest);

    /**
     * 
     * @param getOptionRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetOptionResponseType
     */
    @WebMethod(operationName = "GetOption", action = "ProductService#GetOption")
    @WebResult(name = "GetOptionResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOptionResponse")
    public GetOptionResponseType getOption(
        @WebParam(name = "GetOptionRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOptionRequest")
        GetOptionRequestType getOptionRequest);

    /**
     * 
     * @param getOriginAreaListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetOriginAreaListResponseType
     */
    @WebMethod(operationName = "GetOriginAreaList", action = "ProductService#GetOriginAreaList")
    @WebResult(name = "GetOriginAreaListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOriginAreaListResponse")
    public GetOriginAreaListResponseType getOriginAreaList(
        @WebParam(name = "GetOriginAreaListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOriginAreaListRequest")
        GetOriginAreaListRequestType getOriginAreaListRequest);

    /**
     * 
     * @param getProductRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetProductResponseType
     */
    @WebMethod(operationName = "GetProduct", action = "ProductService#GetProduct")
    @WebResult(name = "GetProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductResponse")
    public GetProductResponseType getProduct(
        @WebParam(name = "GetProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductRequest")
        GetProductRequestType getProductRequest);

    /**
     * 
     * @param getProductListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetProductListResponseType
     */
    @WebMethod(operationName = "GetProductList", action = "ProductService#GetProductList")
    @WebResult(name = "GetProductListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductListResponse")
    public GetProductListResponseType getProductList(
        @WebParam(name = "GetProductListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductListRequest")
        GetProductListRequestType getProductListRequest);

    /**
     * 
     * @param getSubCategoryListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetSubCategoryListResponseType
     */
    @WebMethod(operationName = "GetSubCategoryList", action = "ProductService#GetSubCategoryList")
    @WebResult(name = "GetSubCategoryListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubCategoryListResponse")
    public GetSubCategoryListResponseType getSubCategoryList(
        @WebParam(name = "GetSubCategoryListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubCategoryListRequest")
        GetSubCategoryListRequestType getSubCategoryListRequest);

    /**
     * 
     * @param getSubOriginAreaListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetSubOriginAreaListResponseType
     */
    @WebMethod(operationName = "GetSubOriginAreaList", action = "ProductService#GetSubOriginAreaList")
    @WebResult(name = "GetSubOriginAreaListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubOriginAreaListResponse")
    public GetSubOriginAreaListResponseType getSubOriginAreaList(
        @WebParam(name = "GetSubOriginAreaListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubOriginAreaListRequest")
        GetSubOriginAreaListRequestType getSubOriginAreaListRequest);

    /**
     * 
     * @param getSupplementProductRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetSupplementProductResponseType
     */
    @WebMethod(operationName = "GetSupplementProduct", action = "ProductService#GetSupplementProduct")
    @WebResult(name = "GetSupplementProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSupplementProductResponse")
    public GetSupplementProductResponseType getSupplementProduct(
        @WebParam(name = "GetSupplementProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSupplementProductRequest")
        GetSupplementProductRequestType getSupplementProductRequest);

    /**
     * 
     * @param manageOptionRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageOptionResponseType
     */
    @WebMethod(operationName = "ManageOption", action = "ProductService#ManageOption")
    @WebResult(name = "ManageOptionResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageOptionResponse")
    public ManageOptionResponseType manageOption(
        @WebParam(name = "ManageOptionRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageOptionRequest")
        ManageOptionRequestType manageOptionRequest);

    /**
     * 
     * @param manageProductRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageProductResponseType
     */
    @WebMethod(operationName = "ManageProduct", action = "ProductService#ManageProduct")
    @WebResult(name = "ManageProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageProductResponse")
    public ManageProductResponseType manageProduct(
        @WebParam(name = "ManageProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageProductRequest")
        ManageProductRequestType manageProductRequest);

    /**
     * 
     * @param manageSupplementProductRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageSupplementProductResponseType
     */
    @WebMethod(operationName = "ManageSupplementProduct", action = "ProductService#ManageSupplementProduct")
    @WebResult(name = "ManageSupplementProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageSupplementProductResponse")
    public ManageSupplementProductResponseType manageSupplementProduct(
        @WebParam(name = "ManageSupplementProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageSupplementProductRequest")
        ManageSupplementProductRequestType manageSupplementProductRequest);

    /**
     * 
     * @param deleteProductRequest
     * @return
     *     returns com.nhncorp.platform.shopn.DeleteProductResponseType
     */
    @WebMethod(operationName = "DeleteProduct", action = "ProductService#DeleteProduct")
    @WebResult(name = "DeleteProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "DeleteProductResponse")
    public DeleteProductResponseType deleteProduct(
        @WebParam(name = "DeleteProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "DeleteProductRequest")
        DeleteProductRequestType deleteProductRequest);

    /**
     * 
     * @param getAllOriginAreaListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetAllOriginAreaListResponseType
     */
    @WebMethod(operationName = "GetAllOriginAreaList", action = "ProductService#GetAllOriginAreaList")
    @WebResult(name = "GetAllOriginAreaListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllOriginAreaListResponse")
    public GetAllOriginAreaListResponseType getAllOriginAreaList(
        @WebParam(name = "GetAllOriginAreaListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllOriginAreaListRequest")
        GetAllOriginAreaListRequestType getAllOriginAreaListRequest);

    /**
     * 
     * @param getModificationRequiredProductListRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetModificationRequiredProductListResponseType
     */
    @WebMethod(operationName = "GetModificationRequiredProductList", action = "ProductService#GetModificationRequiredProductList")
    @WebResult(name = "GetModificationRequiredProductListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModificationRequiredProductListResponse")
    public GetModificationRequiredProductListResponseType getModificationRequiredProductList(
        @WebParam(name = "GetModificationRequiredProductListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModificationRequiredProductListRequest")
        GetModificationRequiredProductListRequestType getModificationRequiredProductListRequest);

    /**
     * 
     * @param manageMobileImageInfoRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageMobileImageInfoResponseType
     */
    @WebMethod(operationName = "ManageMobileImageInfo", action = "ProductService#ManageMobileImageInfo")
    @WebResult(name = "ManageMobileImageInfoResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageMobileImageInfoResponse")
    public ManageMobileImageInfoResponseType manageMobileImageInfo(
        @WebParam(name = "ManageMobileImageInfoRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageMobileImageInfoRequest")
        ManageMobileImageInfoRequestType manageMobileImageInfoRequest);

    /**
     * 
     * @param getMobileImageInfoRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetMobileImageInfoResponseType
     */
    @WebMethod(operationName = "GetMobileImageInfo", action = "ProductService#GetMobileImageInfo")
    @WebResult(name = "GetMobileImageInfoResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetMobileImageInfoResponse")
    public GetMobileImageInfoResponseType getMobileImageInfo(
        @WebParam(name = "GetMobileImageInfoRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetMobileImageInfoRequest")
        GetMobileImageInfoRequestType getMobileImageInfoRequest);

    /**
     * 
     * @param restoreProductRequest
     * @return
     *     returns com.nhncorp.platform.shopn.RestoreProductResponseType
     */
    @WebMethod(operationName = "RestoreProduct", action = "ProductService#RestoreProduct")
    @WebResult(name = "RestoreProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "RestoreProductResponse")
    public RestoreProductResponseType restoreProduct(
        @WebParam(name = "RestoreProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "RestoreProductRequest")
        RestoreProductRequestType restoreProductRequest);

    /**
     * 
     * @param getStandardOptionCategoryRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetStandardOptionCategoryResponseType
     */
    @WebMethod(operationName = "GetStandardOptionCategory", action = "ProductService#GetStandardOptionCategory")
    @WebResult(name = "GetStandardOptionCategoryResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetStandardOptionCategoryResponse")
    public GetStandardOptionCategoryResponseType getStandardOptionCategory(
        @WebParam(name = "GetStandardOptionCategoryRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetStandardOptionCategoryRequest")
        GetStandardOptionCategoryRequestType getStandardOptionCategoryRequest);

    /**
     * 
     * @param manageStandardOptionRequest
     * @return
     *     returns com.nhncorp.platform.shopn.ManageStandardOptionResponseType
     */
    @WebMethod(operationName = "ManageStandardOption", action = "ProductService#ManageStandardOption")
    @WebResult(name = "ManageStandardOptionResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageStandardOptionResponse")
    public ManageStandardOptionResponseType manageStandardOption(
        @WebParam(name = "ManageStandardOptionRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageStandardOptionRequest")
        ManageStandardOptionRequestType manageStandardOptionRequest);

    /**
     * 
     * @param getStandardOptionRequest
     * @return
     *     returns com.nhncorp.platform.shopn.GetStandardOptionResponseType
     */
    @WebMethod(operationName = "GetStandardOption", action = "ProductService#GetStandardOption")
    @WebResult(name = "GetStandardOptionResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetStandardOptionResponse")
    public GetStandardOptionResponseType getStandardOption(
        @WebParam(name = "GetStandardOptionRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetStandardOptionRequest")
        GetStandardOptionRequestType getStandardOptionRequest);

}
